### ISSUE TITLE
Support for private feeds

### ISSUE THREAD

**Issue by cweiske** [wltb/ff_instagram#1]
I registered at instagram to follow the posts of a private account, whose posts are of course not visible on the web without logging in.

**Comment by wltb** [comment]
Yes, indeed. Since I don't have an Instagram account and won't create one in the foreseeable future, I did not cover this case and couldn't test any code I would write.

So if you want this feature, you would have to implement it yourself I'm afraid.  Some hints: You probably would do the login (dunno what you have to do there) in the `hook_fetch_feed` function so you could use the user/pass fields provided by ttrss. Then you would have to check if the json this plugin fetches is the same as for public accounts.
