### ISSUE TITLE
No longer working, for me. LibXML error 68 at line 47 (column 40): xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by alexmicuplusfour** [wltb/ff_instagram#8]
LibXML error 68 at line 47 (column 40): xmlParseEntityRef: no name

**Comment by wltb** [comment]
Right. ATM, user pages get redirected to a login page, there's nothing I can do about that.

**Comment by alexmicuplusfour** [comment]
It was nice while it lasted. thanks!

**Comment by wltb** [comment]
Turns out that there is something I can do after all. I already have some code in rough shape, and hope to polish it this week.

**Comment by alexmicuplusfour** [comment]
awesome!

**Comment by mr-bobdobalina** [comment]
A lot of us over at RSS-Bridge are seeing the same thing. IG seems to have implemented some sort of rate limiting. I've set my Instagram feed's update intervals to once daily, it helps, but I still get rate limited.  Perhaps some sort of randomized interval update would help.

**Comment by ALERTua** [comment]
so, is the deskgram workaround considered stable?

**Comment by alexmicuplusfour** [comment]
I set mine to update daily, and it works now. thanks @mr-bobdobalina

**Comment by wltb** [comment]
> so, is the deskgram workaround considered stable?

Instagram decided to re-enable public profiles, so ATM it seems better to use the old code since deskgram randomly decides that it doesn't know profiles, and timestamps are more precise.

I'll have to work on the code structure so I can easily add other sites and use them as mutual fallbacks, but the deskgram scraper in itself is as good as I can do it.
